# CircleCI configuration file
version: 2.1

jobs:
  # Job one with a unique name
  say_hello:
    docker:
      - image: cimg/base:2022.05
    steps:
      - run: echo "Say hello to circleCI4!"
  # Job two with a unique name
  say_goodbye:
    docker:
      - image: cimg/base:2022.05
    steps:
      - run: echo "Say goodbye to circleCI4!"

workflows:
  # Name of workflow
  hello_and_goodbye:
    # List of jobs that will run
    jobs:
      - say_hello
      - say_goodbye
